### ISSUE TITLE
Discolouration on subtitles

### ISSUE THREAD

**Issue by Jules-A** [Artoriuz/glsl-chroma-from-luma-prediction#4] opened 2023-10-10 16:00 UTC
Tested after the changes from master, it doesn't discolour any less but it only seems to be yellow now which is less noticeable:
12:
![mpv-shot0001](https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/assets/1760158/493bdd41-5011-417b-8340-fc90d6317970)

Oddly enough it is slightly less noticeable in mixed and even less so with 4 although you can briefly see blues.

**Comment by Artoriuz** [comment] 2023-10-10 16:06
I don't remember the exact value from when I tested this yesterday but I think setting division_limit to 1e-3 fixes this (albeit with quality losses elsewhere).

**Comment by Jules-A** [comment] 2023-10-10 16:12
> I don't remember the exact value from when I tested this yesterday but I think setting division_limit to 1e-3 fixes this (albeit with quality losses elsewhere).

I tested 1e-3 and 1e-2 and both exhibit the issue still.

**Comment by Artoriuz** [comment] 2023-10-16 15:57
Can you retest to see if this is still happening? Many changes were made since last week.

**Comment by Jules-A** [comment] 2023-10-16 16:38
> Can you retest to see if this is still happening? Many changes were made since last week.

I accidentally deleted the series after I finished it out of habit and don't have a CR sub right now :/
If it helps I tried reproducing on a few other subs with the newer version and didn't manage to spot the issue. Maybe I will try with an image I posted here lol, if that even works.

EDIT: I could only find the image of an already upscaled screenshot and couldn't see it occur on that but not apples to apples...

**Comment by Artoriuz** [comment] 2023-10-16 16:44
Alright, thanks. I can't reproduce it on anything I have currently downloaded either so I guess we can close this too.

**Closed as completed by Artoriuz** 2023-10-16 16:44 UTC

**Comment by Jules-A** [comment] 2023-10-16 17:04
This change: https://github.com/Artoriuz/glsl-chroma-from-luma-prediction/commit/8176605fa3983f3fa7e46566a50f14aba8a6bf90 introduced a decent bit of ringing though.
EDIT: Nvm it's only ever so slightly worse, it might have been a previous change or maybe mix always had that much ringing as I was testing 12tap before.

**Comment by Artoriuz** [comment] 2023-10-16 19:27
The new spatial filter (polar approximation of lanczos) is sharper than the old one, and I've also loosened the AR a little bit.

I should probably make AR configurable though (and reevaluate the default strength again since things changed...)
